### ISSUE TITLE
It can't serialize a array member

### ISSUE THREAD

**Issue by zhangdexin** [fraillt/bitsery#107]
```
struct MyStruct
{
  uint32_t i;
  MyEnum e;
  std::vector<float> fs;
  int arr[10] = {0};
};
```

```
 MyStruct data;
  data.i = 999;
  data.arr[6] = 984;
```
when unserialize to res, it canot get res.arr[6] is 984

**Comment by fraillt** [comment]
Show me your serialize function, I assume it misses `arr` field.

**Comment by zhangdexin** [comment]
oh yeah, I miss arr field, tks.
But I want to kown if has solution that no need user define `serialize function`. like [struct_pack](https://github.com/alibaba/yalantinglibs/tree/main/src/struct_pack) on c++17

**Comment by fraillt** [comment]
You can check #104 there are some useful code snippets that serializes POD structs, but it requires c++20 and still doesn't work with all POD types.

**Comment by zhangdexin** [comment]
tks~
