### ISSUE TITLE
User-defined `deserialize` function?

### ISSUE THREAD

**Issue by DUOLabs333** [fraillt/bitsery#112]
Can we just define a custom `deserialize` function the same way we do for `serialize`?

**Comment by Kubic-C** [comment]
I believe the serialize function acts as both the deserialization and serialization function. I wonder what your use case is?

**Comment by DUOLabs333** [comment]
Well, for example, I sometimes want a struct to be deserialized differently than how it's serialized (eg, I get some new information back that I need to specially handle).

**Comment by fraillt** [comment]
Bitsery uses so called `extensions` to achieve this.
The idea is that you usually describe (declare) how particular struct will be serialized and deserialized, but extensions allow to customize how actual serialization and deserialization is implemented for particular type.
You can try to look in [tutorials](https://github.com/fraillt/bitsery/tree/master/doc/tutorial), or directly into bunch of [extensions](https://github.com/fraillt/bitsery/tree/master/include/bitsery/ext) implementation.

**Comment by DUOLabs333** [comment]
Thanks.
