### ISSUE TITLE
Build failure on newer clang (LLVM 17)

### ISSUE THREAD

**Issue by VelocityRa** [fraillt/bitsery#115]
At least one issue is that `adapter_common.h` includes `<cstdint>` but uses `uint8_t` etc types, even though these are only guaranteed to exist under `std::` (unlike with `stdint.h`).

**Comment by fraillt** [comment]
mmm... you're right :/ maybe I should update this. It should be hard though basically search/replace all `intX_t`, `uintX_t` and `size_t` by adding `std::` prefix.

**Comment by VelocityRa** [comment]
Why not just include `<stdint.h>` instead?

**Comment by VelocityRa** [comment]
No need as long as you make a new release :) see https://github.com/fraillt/bitsery/pull/117#issuecomment-2254502894
