### ISSUE TITLE
Recreate Pointer Objects w/ Custom Allocator During Deserialization

### ISSUE THREAD

**Issue by victorstewart** [fraillt/bitsery#13]
title is pretty self explanatory :)

i have some objects i'm currently using new to allocate, but want to switch over to using a custom allocator. i serialize/deserialize these objects with bitsery, and so would need the custom allocator to be triggered upon deserialization.

maybe i missed it but i didn't see any hooks to allocate memory when deserializing a pointer.

**Comment by fraillt** [comment]
Hello,
You're right at the moment there is no hook for custom allocator for pointers. It should be added in 
https://github.com/fraillt/bitsery/blob/master/include/bitsery/details/serialization_common.h `bitsery::Access::createInHeap` method, but I haven't decided yet of how it should be implemented.
The best place to add allocator hook is probably in `PointerLinkingContext`, and I would like to add `std::pmr::polymorphic_allocator<T>` but that requires c++17, on the other hand I don't have much experience using it, and would like to avoid bad design desitions, that could limit some use cases.
If you are familiar with bitsery codebase, maybe you have suggestions of how it could be done? :)

**Comment by fraillt** [comment]
Lately, I was thinking about how to implement this, but allocating polymorphic types, means that I need to register functions matrix (types * allocators).
I would like to know what is sufficient/minimum functionality for you to use a custom allocator, maybe we can add this feature in multiple steps. 
It would be much simpler to implement it if we could allocate only void*, but is it sufficient functionality?

**Comment by victorstewart** [comment]
@fraillt sorry forgot to follow up!

Is there a problem with requiring C++17, even if just to activate this single feature? It is 2019 :)

My use case I'm using [rpmalloc](https://github.com/rampantpixels/rpmalloc) to allocate a single custom class. So `void*` is great! Just a matter of `sizeof(T)`.

When could void* not be sufficient? I guess just because of type-explicit paradigms?

**Comment by victorstewart** [comment]
[https://stackoverflow.com/questions/38010544/polymorphic-allocator-when-and-why-should-i-use-it](https://stackoverflow.com/questions/38010544/polymorphic-allocator-when-and-why-should-i-use-it)

this QxA has a nice overview of `std::pmr::polymorphic_allocator<T>`, and it seems the point is just to allow containers of `T` with varying possible allocators to share a single type.

**Comment by fraillt** [comment]
It`s not a problem to add C++17 feature, I just did it with few latest extensions :)
I just want to leave core functionality C++11 compatible.
If `void*` is sufficient then I have an idea how to do it ;)
I think it will be flexible enough if I provide type alignment, type size and type "typeid" (from RTTI) for allocation, to implement any functionality.
I hope that I'll have some time and hopefully have something in develop branch next week :)

**Comment by fraillt** [comment]
Hello,
I finally managed to complete custom allocator support for a pointer like types. It was more work than expected :) I also wrote brief information on how to use them and about pointer in general [here](https://github.com/fraillt/bitsery/blob/develop/doc/design/pointers.md).
Currently, an implementation is only in develop branch.
I would appreciate if you could provide any feedback on this :)

**Comment by victorstewart** [comment]
you have my full attention tomorrow! i’ll send over a sample program

**Comment by fraillt** [comment]
Added ability to customize memory allocation in bitsery 5.0.0.
More details about memory allocation can be found [here](https://github.com/fraillt/bitsery/blob/master/doc/design/pointers.md).
Have fun ;)
