### ISSUE TITLE
Support for union/variant types

### ISSUE THREAD

**Issue by vhdirk** [fraillt/bitsery#15]
Hi,

Do you have any plans to add support for union types (like in FlatBuffers)?
Or, if not, would you have any example for achieving something similar?

**Comment by fraillt** [comment]
Hello,

Yes, I have plans to add `<variant>`, as well as `<chrono>` types. Hope, that I'll be able to do it in 1-2 weeks.

**Comment by fraillt** [comment]
Support for variant and tuple added in [v4.6.0](https://github.com/fraillt/bitsery/releases/tag/v4.6.0) have fun ;)
