### ISSUE TITLE
Serializing std::function and SG14 stdext::inplace_function objects?

### ISSUE THREAD

**Issue by victorstewart** [fraillt/bitsery#20]
According to the discussions in the comments on this answer,[https://stackoverflow.com/a/22772214/5689597](https://stackoverflow.com/a/22772214/5689597), it seems std::function objects should be serializable as long as they are deserialized on the same architecture!

Here's an implementation of it done: [https://github.com/darabos/pinty/blob/master/pinty.h](https://github.com/darabos/pinty/blob/master/pinty.h)

And if so, then certainly the new SG14 function objects ([https://github.com/WG21-SG14/SG14/blob/master/SG14/inplace_function.h](https://github.com/WG21-SG14/SG14/blob/master/SG14/inplace_function.h)) with explicitly defined memory buffer capacities must be able to be too?

Of course they have to be capture-less though!

I have time this week to immerse myself in the bitsery code base to suggest and draft implementations of these additions and the others I've mentioned. So if you want we can discuss and coordinate?

**Comment by fraillt** [comment]
It might be interesting to be able to serialize function objects, I don't mind to see your implementation :)
I didn't have much time lately, and I'm still working on #13, actually almost finished, but i'm not enterily happy with my current implementation, but I hope i'll polish it this week.
Do you also have ideas on how #19 should look?

**Comment by victorstewart** [comment]
here’s the background on the function objects...

so my app persists it’s state with bitsery, and is expected to retain what it’s been passed, except in the case of crashes. 

my update pipeline passes new information from server to app... and then updating the database (really just standard containers wrapped in a class) and views requires semi-strict ordering by time and type, plus synchronization with what’s currently on screen (aka UI thread vs background threads). 

So the only sensible way is to package these as function objects, then update batches, and queue them— and erase as consumed.

but there are of course edges where the app will terminate before i’ve had a chance to execute all queued updates. so if not for persisting the function objects, would have to repeat all the processing work plus solve the puzzle of what’s been completed.

**Comment by fraillt** [comment]
Closing, because I don't see a solution, that would work cross-platform. I encourage to try and implement your own extension.
