### ISSUE TITLE
Serializing Strings and Vectors

### ISSUE THREAD

**Issue by victorstewart** [fraillt/bitsery#22]
both of these fail with these compiler errors. I guess these weren't imagined to be serialized on their own? I'm sure there's some quick tweak to make.

```
#include <bitsery/bitsery.h>
#include <bitsery/adapter/buffer.h>

#include <string>
#include <vector>

#include <bitsery/traits/vector.h>
#include <bitsery/traits/string.h>

using Buffer = std::vector<uint8_t>;

using InputAdapter = bitsery::InputBufferAdapter<Buffer>;
using OutputAdapter = bitsery::OutputBufferAdapter<Buffer>;

int main (int argc, char* argv[], char* env[])
{
   std::basic_string<char> token;
   Buffer tokenData;
   (void)bitsery::quickSerialization<OutputAdapter>(tokenData, token);
   (void)bitsery::quickDeserialization(InputAdapter(tokenData.begin(), tokenData.size()), token);

    
   std::vector<Buffer> buffers;
   Buffer buffersData;
   (void)bitsery::quickSerialization<OutputAdapter>(buffersData, buffers);
   (void)bitsery::quickDeserialization(InputAdapter(buffersData.begin(), buffersData.size()), buffers);
   return 1;
}
```
> root@7342c4214c33 /root # g++ -std=gnu++17 -I/root/bitsery/include -L/usr/local/lib -lulib_g -o bitsery.test /root/test/bitsery.test.cpp
> In file included from /root/bitsery/include/bitsery/serializer.h:27,
>                  from /root/bitsery/include/bitsery/bitsery.h:40,
>                  from /root/test/bitsery.test.cpp:1:
> /root/bitsery/include/bitsery/details/serialization_common.h: In instantiation of ‘static void bitsery::details::SerializeFunction<S, T>::invoke(S&, T&) [with S = bitsery::BasicSerializer<bitsery::AdapterWriter<bitsery::OutputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>, void>; T = std::__cxx11::basic_string<char>]’:
> /root/bitsery/include/bitsery/serializer.h:84:67:   required from ‘void bitsery::BasicSerializer<TAdapterWriter, TContext>::object(const T&) [with T = std::__cxx11::basic_string<char>; TAdapterWriter = bitsery::AdapterWriter<bitsery::OutputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>; TContext = void]’
> /root/bitsery/include/bitsery/serializer.h:427:9:   required from ‘size_t bitsery::quickSerialization(Adapter, const T&) [with Adapter = bitsery::OutputBufferAdapter<std::vector<unsigned char> >; T = std::__cxx11::basic_string<char>; size_t = long unsigned int]’
> /root/test/bitsery.test.cpp:19:69:   required from here
> /root/bitsery/include/bitsery/details/serialization_common.h:234:65: error: static assertion failed: 
> Please define 'serialize' function for your type (inside or outside of class):
>   template<typename S>
>   void serialize(S& s)
>   {
>     ...
>   }
> 
>                  static_assert(HasSerializeFunction<S, T>::value || HasSerializeMethod<S, T>::value,
>                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /root/bitsery/include/bitsery/details/serialization_common.h: In instantiation of ‘static void bitsery::details::SerializeFunction<S, T>::invoke(S&, T&) [with S = bitsery::BasicDeserializer<bitsery::AdapterReader<bitsery::InputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>, void>; T = std::__cxx11::basic_string<char>&]’:
> /root/bitsery/include/bitsery/deserializer.h:86:69:   required from ‘void bitsery::BasicDeserializer<TAdapterReader, TContext>::object(T&&) [with T = std::__cxx11::basic_string<char>&; TAdapterReader = bitsery::AdapterReader<bitsery::InputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>; TContext = void]’
> /root/bitsery/include/bitsery/deserializer.h:436:9:   required from ‘std::pair<bitsery::ReaderError, bool> bitsery::quickDeserialization(Adapter, T&) [with Adapter = bitsery::InputBufferAdapter<std::vector<unsigned char> >; T = std::__cxx11::basic_string<char>]’
> /root/test/bitsery.test.cpp:20:96:   required from here
> /root/bitsery/include/bitsery/details/serialization_common.h:234:65: error: static assertion failed: 
> Please define 'serialize' function for your type (inside or outside of class):
>   template<typename S>
>   void serialize(S& s)
>   {
>     ...
>   }
> 
> /root/bitsery/include/bitsery/details/serialization_common.h: In instantiation of ‘static void bitsery::details::SerializeFunction<S, T>::invoke(S&, T&) [with S = bitsery::BasicSerializer<bitsery::AdapterWriter<bitsery::OutputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>, void>; T = std::vector<std::vector<unsigned char> >]’:
> /root/bitsery/include/bitsery/serializer.h:84:67:   required from ‘void bitsery::BasicSerializer<TAdapterWriter, TContext>::object(const T&) [with T = std::vector<std::vector<unsigned char> >; TAdapterWriter = bitsery::AdapterWriter<bitsery::OutputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>; TContext = void]’
> /root/bitsery/include/bitsery/serializer.h:427:9:   required from ‘size_t bitsery::quickSerialization(Adapter, const T&) [with Adapter = bitsery::OutputBufferAdapter<std::vector<unsigned char> >; T = std::vector<std::vector<unsigned char> >; size_t = long unsigned int]’
> /root/test/bitsery.test.cpp:25:73:   required from here
> /root/bitsery/include/bitsery/details/serialization_common.h:234:65: error: static assertion failed: 
> Please define 'serialize' function for your type (inside or outside of class):
>   template<typename S>
>   void serialize(S& s)
>   {
>     ...
>   }
> 
> /root/bitsery/include/bitsery/details/serialization_common.h: In instantiation of ‘static void bitsery::details::SerializeFunction<S, T>::invoke(S&, T&) [with S = bitsery::BasicDeserializer<bitsery::AdapterReader<bitsery::InputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>, void>; T = std::vector<std::vector<unsigned char> >&]’:
> /root/bitsery/include/bitsery/deserializer.h:86:69:   required from ‘void bitsery::BasicDeserializer<TAdapterReader, TContext>::object(T&&) [with T = std::vector<std::vector<unsigned char> >&; TAdapterReader = bitsery::AdapterReader<bitsery::InputBufferAdapter<std::vector<unsigned char> >, bitsery::DefaultConfig>; TContext = void]’
> /root/bitsery/include/bitsery/deserializer.h:436:9:   required from ‘std::pair<bitsery::ReaderError, bool> bitsery::quickDeserialization(Adapter, T&) [with Adapter = bitsery::InputBufferAdapter<std::vector<unsigned char> >; T = std::vector<std::vector<unsigned char> >]’
> /root/test/bitsery.test.cpp:26:102:   required from here
> /root/bitsery/include/bitsery/details/serialization_common.h:234:65: error: static assertion failed: 
> Please define 'serialize' function for your type (inside or outside of class):
>   template<typename S>
>   void serialize(S& s)
>   {
>     ...
>   }

**Comment by fraillt** [comment]
`quickSerialization/Deserialization` was made to only serialize objects because they don't require any additional information, such as value size or, in case of `std::string` serialize as string or container (`std::string` can necessarily be null-terminated). It might make sense to add additional lambda parameter, that would describe how to serialize particular value, but at this point you should probably just copy/paste implementation and replace `ser.object(value)` with an implementation that you want ;)
*OR*
you can always provide serialize function for the container, but do it in a bitsery namespace, otherwise, ADL will not find it.
e.g.
```cpp
namespace bitsery {
  template <typename S>
  void serialize(S& s, std::vector<Buffer>& c) {
    s.container(c, 1000, [&s](Buffer& b) {
      s.container1b(b, 10000);
    } 
  }
}
```

**Comment by victorstewart** [comment]
ok great. providing the serialization function is good for now, if I need more implicit implementations later I can always play with api extension as you suggest!
