### ISSUE TITLE
separate save/load

### ISSUE THREAD

**Issue by cdcseacave** [fraillt/bitsery#29]
I am not an user yet, though the list of features is impressive and complete. I use currently boost serialization, and I think I'll be able to transition quite smoothly, except for one thing: I need in couple of places to have separate save/load in order to pre/post process some values. U mention this is possible through extensions, but I do not find neither the extension nor an example.
 Can you help pls?

**Comment by fraillt** [comment]
Hello,
All extensions are located [here](https://github.com/fraillt/bitsery/tree/master/include/bitsery/ext).
Core components of an extension is:
1) Extension class itself, which is defined by implementing two template functions `serialize` (save) and `deserialize` (load).
2) `ExtensionTraits` specialization for an extension, which specifies how it should be used.

I wrote a simple implementation that accepts serialize and deserialize callable objects.
```cpp

namespace bitsery {
    namespace ext {

        template <typename SerFnc, typename DesFnc>
        class SaveAndLoad{
        public:
            SaveAndLoad(SerFnc serFnc, DesFnc desFnc)
                :_serFnc{std::move(serFnc)},
                _desFnc{std::move(desFnc)} {}

            template<typename Ser, typename T, typename Fnc>
            void serialize(Ser& ser, const T& obj, Fnc&& ) const {
                _serFnc(ser,obj);
            }

            template<typename Des, typename T, typename Fnc>
            void deserialize(Des& des, T& obj, Fnc&& ) const {
                _desFnc(des, obj);
            }
        private:
            std::decay_t<SerFnc> _serFnc;
            std::decay_t<DesFnc> _desFnc;
        };
    }

    namespace traits {
        template<typename T, typename SerFnc, typename DesFnc>
        struct ExtensionTraits<ext::SaveAndLoad<SerFnc, DesFnc>, T> {
            using TValue = void;
            static constexpr bool SupportValueOverload = false;
            static constexpr bool SupportObjectOverload = true;
            static constexpr bool SupportLambdaOverload = false;
        };

    }

}
```

And if you use C++17, you can use it like this (using with C++11 is not convenient because it requires to specify template parameters for `SaveAndLoad`):
```cpp
    s.ext(o.my_type, bitsery::ext::SaveAndLoad(
        [](auto& ser, const MyType& obj) { ... }, // save function
        [](auto& des, MyType& obj) { ... })); //load function
```

If you only want this functionality only for a few types, you can write extension exactly for that type.
```cpp
namespace bitsery {
    namespace ext {

        class SaveLoadMyType {
        public:
            template<typename Ser, typename Fnc>
            void serialize(Ser& ser, const MyType& obj, Fnc&& ) const {
               ...
            }

            template<typename Des, typename Fnc>
            void deserialize(Des& des, MyType& obj, Fnc&& ) const {
               ...
            }
        };
    }

    namespace traits {
        template<typename T>
        struct ExtensionTraits<ext::SaveLoadMyType, T> {
            using TValue = void;
            static constexpr bool SupportValueOverload = false;
            static constexpr bool SupportObjectOverload = true;
            static constexpr bool SupportLambdaOverload = false;
        };

    }
}
```
You can use this like this.
```cpp
s.ext(o.my_type, bitsery::ext::SaveLoadMyType{});
```

Hope that helped ;)

**Comment by cdcseacave** [comment]
This is very helpful, I'll try it with the first occasion. Thank you!

**Comment by fraillt** [comment]
Since extensions are at the core of bitsery, I wrote more detailed information on their design [here](https://github.com/fraillt/bitsery/blob/develop/doc/design/extensions.md).
I believe it will be useful for many users :)
