### ISSUE TITLE
includes are inconsistent

### ISSUE THREAD

**Issue by tower120** [fraillt/bitsery#36]
Some of #include's in your library have relative path, some "absolute". Like:

```cpp
#ifndef BITSERY_BRIEF_SYNTAX_TYPE_STD_ARRAY_H
#define BITSERY_BRIEF_SYNTAX_TYPE_STD_ARRAY_H

#include "../traits/array.h"
#include "bitsery/details/brief_syntax_common.h"

```

If relative paths would used everywhere, it would be possible to just drop in your library, like in my_library/third_party/bitsery. Without additional include paths for compiler/linker. 
IOW another header only library, which uses bitsery, could just have it internally, without additional fuss for end-user.

**Comment by fraillt** [comment]
Hello,
Indeed, this is not correct, all internal files should use relative path.
You can do a PR, if you have fixed all paths. :)

**Comment by tower120** [comment]
I fixed part of them. Then just discarded everything, and added includepath...

**Comment by fraillt** [comment]
Fixed it in develop branch
