### ISSUE TITLE
buffer.h integer implicit conversion 

### ISSUE THREAD

**Issue by tower120** [fraillt/bitsery#39]
`bitsery/include/bitsery/adapter/buffer.h` have "implicit conversion changes signedness" warnigns all over the place.

Mainly because you adding `std::size_t` to `TIterator`. While `TIterator::operator+(diff_t)`.
Either make everything diff_t, either use explicit casts:
```cpp
using diff_t = typename std::iterator_traits<TIterator>::difference_type;
diff_t _currOffset{0};
diff_t _bufferSize{0};
diff_t _biggestCurrentPos{0};
```

----

Also, what about run tests with:
```
add_compile_options(-Wall -Wextra -Wconversion -pedantic -Werror)
```
?

**Comment by fraillt** [comment]
Yes, adding -Wconversion shows a lot of warnings.
There are already some compile flags added, during tests compilation.
https://github.com/fraillt/bitsery/blob/master/tests/CMakeLists.txt#L42

Would you fix this, and make PR ? :)

**Comment by tower120** [comment]
I already was in process... 
Then I stopped and realize that this is design choice/change that can not be taken lightly...
And that I not understand how it actually should be.... What is "correct".

I could just add casts everywhere - but maybe there is indeed some hidden error behind one of this warnings...

---

Thou, I can fiddle with your CMake and travis files - add more warnings as errors and add ASAN tests runs. But they probably stop passing :))

**Comment by fraillt** [comment]
If you're willing to invest some time and improve things around here, I would be glad to review it as PR.

**Comment by tower120** [comment]
I'll try, later this evening.
