### ISSUE TITLE
MSVC C4310 error

### ISSUE THREAD

**Issue by tower120** [fraillt/bitsery#43]
msvc 17 gave C4310 error (truncating constant value) here:
```cpp
        struct EndiannessTestData {
            static constexpr uint32_t _sample4Bytes = 0x01020304;
            static constexpr uint8_t _sample1stByte = (const uint8_t &) _sample4Bytes;
        };
```
Why you cast to reference? This will not have the same effect ?
```cpp
            static constexpr uint8_t _sample1stByte = static_cast<uint8_t>(_sample4Bytes);
```

**Comment by fraillt** [comment]
No it is not the same. with static_cast it will be the same on big or little endian platforms (and it will always be 0x04).
What this does is gets address of 4byte length integer type, and gets its lowest byte, in case of little endian platform lowest byte would have 0x04, and for big endian platform it would be 0x01. 
Don't know how to fix this..., in C++20 there is a standard way to check endianess, there are other ways to check it, for example there are multiple examples that checks it with union, but it is undefined behaviour.
