### ISSUE TITLE
adapter/stream require rtti

### ISSUE THREAD

**Issue by tower120** [fraillt/bitsery#44]
`BasicBufferedOutputStreamAdapter::flush()` have dynamic_cast from `basic_ios` to `basic_ostream`.
What if BasicBufferedOutputStreamAdapter will work directly with basic_ostream?
I mean, constructor accept `basic_ostream` and store it as `basic_ostream`.

**Comment by fraillt** [comment]
You're right, this should work and it would remove a dynamic cast.
The same must be done with BasicInputStreamAdapter and then we should fix BasicIOStreamAdapter as well.
Could you do that as well, and make PR? :)
