### ISSUE TITLE
Serializing forward-declared types

### ISSUE THREAD

**Issue by VelocityRa** [fraillt/bitsery#49]
I have a bunch of forward declares for types used in my classes and in order to use bitsery it looks like I need to include the headers for them (forward declaring doesn't work).

More of a detail:
I use forward declares because I hold raw pointers to my types, but I don't actually use bitsery's raw pointer features because I manage the memory/hierarchy myself.
Instead I serialize them dereferenced.

Anyway, is there a way to avoid having the includes? Using forward declares is better practice.

Thanks, great library :)

**Comment by tower120** [comment]
You could put your serialize() global functions into separate header... And include them just before you actually do serialization....

```cpp
// MyData.h
struct MyData{};

// MyDataSerialization.h
#include "MyData.h"

template<class S>
void serializer(S&s, MyData& data){}
```

You can't serialize only forward declared type, because you need somehow to access its internal structure to actually get data from it.

**Comment by VelocityRa** [comment]
Hm, I think you could do this with `cereal`. Might be wrong.

**Comment by tower120** [comment]
You have to include concrete class at some point... Either I misunderstood you...

**Comment by fraillt** [comment]
Somewhere you have to define serialize function for concrete type, and the you can have forward declares for your type and serialize function.

**Comment by VelocityRa** [comment]
Right. And the serialize function is templated so you can't define it in a .cpp file, so it sounds like it's not possible then.
Thanks for answering.

**Comment by tower120** [comment]
Include your serialization code/header only in .cpp:

```cpp
// MyData.h
struct MyData{
    int data;
};

// MyDataSerialize.h
#include "MyData.h"
template<class S>
void serialize(S& s, MyData&){}

// Hub.h
struct MyData;
struct Hub{
    MyData* data;
};

// Serialize.h
struct MyData;
struct Serialize{
   void save(MyData*);
};
// Serialize.cpp
#include "MyDataSerialize.h"
void save(MyData* data){
   // do serialization here.
}
```

**Comment by VelocityRa** [comment]
@tower120 I don't really get how this would work. Who calls `save`? I don't see bitsery do that anywhere. It only sees `serialize` which is empty there.

**Comment by VelocityRa** [comment]
Because now I include headers in so many places in my codebase, I get cyclic dependencies which are hard to debug :/

**Comment by VelocityRa** [comment]
And I still don't know how to fix this. Everyone recommends to use forward declares, but I can't do that now.

**Comment by VelocityRa** [comment]
'Fixed' by defining the `serialize` function in the `.cpp` file, by forward declaring the template parameters... super hacky but works.

**Comment by fraillt** [comment]
I'm glad that you resolved, it sounds "hacky", but I think its the only way around this.
