### ISSUE TITLE
Make quickSerialization() usable for streams

### ISSUE THREAD

**Issue by VelocityRa** [fraillt/bitsery#55]
That's because `writtenBytesCount` is not implemented for it, but can't it _be_ implemented by using `std::ostream::tellp`? By storing the start in the constructor and then returning the difference, when `writtenBytesCount()` is called.

Is that possible or am I missing something?

**Comment by fraillt** [comment]
It is doable, but there are reasons why it's not done.
* `tellp` depends on the underlying `streambuf` implementation (there are no guarantees that it would actually return correct position), the other problem is that Stream/BufferAdapter itself doesn't own stream/buffer, which means that if you use the same stream multiple times, `tellp` will lie to you :)
* Other option would be to track written bytes manually in a stream adapter, which is kinda ok, but it adds unnecessary (although very minor) overhead and there already exists `MeasureSize` adapter for exactly this purpose.
* Stream is conceptually different from a buffer. With a buffer you basically loop through these steps: clear, write, copy. But with a stream, you only write all the time and that's it.

Hope that this would make more sense now.

**Comment by VelocityRa** [comment]
Hmm I see.
Thanks for the detailed explanation 👍
