### ISSUE TITLE
Delta encoding

### ISSUE THREAD

**Issue by domgho** [fraillt/bitsery#56]
Tests show that using [delta encoding](https://en.wikipedia.org/wiki/Delta_encoding) on my serialized data before compressing reduces file size.

According to https://libraries.io/github/fraillt/bitsery delta encoding might have already been planned:
> [bitsery] is still missing functions for delta changes and geometry compression

How would I best implement delta encoding in Bitsery?

EDIT: After separating serialize into save/load functions by not using the quickSerialization function it's now clear how to do this manually.

**Comment by fraillt** [comment]
Very good point, bitsery indeed is missing delta serialization functions, but this is a broader topic than I initially was expected. Actually bitsery was born from delta serialization, which later was removed entirely for multiple reasons. For curiosity, you can look at [first commit](https://github.com/fraillt/bitsery/commit/0fb7b0986dff09671abe55dd11acbc950573e8d3).
There were classes like `DeltaSerializer` and `DeltaDeserializer`.
Now I think that delta encoding should be done as a separate library, some parts of bitsery could be reused, like Input/OutputAdapter, etc...
Could you elaborate more on how you gonna do delta encoding for your needs?
