### ISSUE TITLE
Lots of unknown pragma warnings with GCC and Clang in bitsery 5.1.0

### ISSUE THREAD

**Issue by robbert-vdh** [fraillt/bitsery#63]
First of all, thanks for making bitsery! I was just about to upgrade my project to bitsery 5.1.0, but I noticed that commit 9cade41dbb9a7b8220d674aba3ff3eb09a410c3b adds a few MSVC-only pragmas. This results in a ton of unknown pragma warnings when compiling on GCC or Clang with `-Wall`. Would it be possible to gate those pragmas behind a compiler check?

**Comment by fraillt** [comment]
Hi, sure i'll try to improve it, but at the moment I' m quite busy.

**Comment by fraillt** [comment]
improved in [v5.2.0](../releases/tag/v5.2.0).
