### ISSUE TITLE
Compilation fails when using map。

### ISSUE THREAD

**Issue by TsinghuaTop** [fraillt/bitsery#65]
i just edit brief_syntax example to using std::map but compilation fails. code as following:

#include <bitsery/adapter/buffer.h>
#include <bitsery/bitsery.h>
//to use brief syntax always include this header
#include <bitsery/brief_syntax.h>
//we also need additional traits to work with container types,
//instead of including <bitsery/traits/vector.h> for vector traits, now we also need traits to work with brief_syntax types.
//so include everything from <bitsery/brief_syntax/...> instead of <bitsery/traits/...>
//otherwise we'll get static assert error, saying to define serialize function.
#include <bitsery/brief_syntax/map.h>
#include <bitsery/brief_syntax/vector.h>

enum class MyEnum : uint16_t { V1, V2, V3 };
struct MyStruct {
    uint32_t i;
    MyEnum e;
    //std::vector<float> fs;
    std::map<std::string, int32_t> fm;

    //define serialize function as usual
    template <typename S>
    void serialize(S& s) {
        //now we can use brief syntax with
        s(i, e, fm);
    }
};

//some helper types
using Buffer = std::vector<uint8_t>;
using OutputAdapter = bitsery::OutputBufferAdapter<Buffer>;
using InputAdapter = bitsery::InputBufferAdapter<Buffer>;

int main() {
    //set some random data
    MyStruct data{8941, MyEnum::V2, {{"xxx", 1}, {"yyy", 2}}};
    MyStruct res{};

    //serialization, deserialization flow is unchanged as in basic usage
    Buffer buffer;
    auto writtenSize = bitsery::quickSerialization<OutputAdapter>(buffer, data);

    auto state = bitsery::quickDeserialization<InputAdapter>({buffer.begin(), writtenSize}, res);
}

and the errors as following

In file included from /Users/bjarneyang/Workspace/incubator/lfe/tests/bitsery_test.cc:70:
In file included from /Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/buffer.h:26:
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../details/adapter_common.h:149:17: warning: unknown pragma ignored [-Wunknown-pragmas]
        #pragma warning( disable : 4310 )
                ^
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../details/adapter_common.h:154:17: warning: unknown pragma ignored [-Wunknown-pragmas]
        #pragma warning( default : 4310 )
                ^
In file included from /Users/bjarneyang/Workspace/incubator/lfe/tests/bitsery_test.cc:71:
In file included from /Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/bitsery.h:40:
In file included from /Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../details/../serializer.h:27:
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../traits/core/../../details/serialization_common.h:249:17: error: static_assert failed due to requirement
      'HasSerializeFunction<bitsery::Serializer<bitsery::OutputBufferAdapter<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, bitsery::DefaultConfig>, void>, std::__1::basic_string<char>, void>::value ||
      HasSerializeMethod<bitsery::Serializer<bitsery::OutputBufferAdapter<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, bitsery::DefaultConfig>, void>, std::__1::basic_string<char>, void>::value' "\nPlease
      define 'serialize' function for your type (inside or outside of class):\n template<typename S>\n void serialize(S& s)\n {\n    ...\n  }\n"
                static_assert(HasSerializeFunction<S, T>::value || HasSerializeMethod<S, T>::value,
                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../details/../serializer.h:178:56: note: in instantiation of member function
      'bitsery::details::SerializeFunction<bitsery::Serializer<bitsery::OutputBufferAdapter<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, bitsery::DefaultConfig>, void>, std::__1::basic_string<char>
      >::invoke' requested here
            details::SerializeFunction<Serializer, T>::invoke(*this, const_cast<T& >(obj));
                                                       ^
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/brief_syntax/map.h:35:21: note: in instantiation of function template specialization
      'bitsery::Serializer<bitsery::OutputBufferAdapter<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, bitsery::DefaultConfig>, void>::object<std::__1::basic_string<char> >' requested here
                  s.object(key);
                    ^
/Users/bjarneyang/Workspace/incubator/lfe/deps/bitsery/include/bitsery/adapter/../traits/core/../../details/serialization_common.h:276:17: note: in instantiation of function template specialization
      'bitsery::serialize<bitsery::Serializer<bitsery::OutputBufferAdapter<std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, bitsery::DefaultConfig>, void>, std::__1::basic_string<char>, int,
      std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, int> > >' requested here
                serialize(s, v);
                ^

**Comment by TsinghuaTop** [comment]
my gcc version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by TsinghuaTop** [comment]
clang 
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by fraillt** [comment]
Hello,
Since map contains std::string, i think you need to include it as well 
```
#include <bitsery/brief_syntax/string.h>
```

**Comment by TsinghuaTop** [comment]
thanks for fraillt very much. it is ok.
