### ISSUE TITLE
Example of serializing into the middle of a buffer?

### ISSUE THREAD

**Issue by Mmpuskas** [fraillt/bitsery#67]
This might be obvious, but I'm having trouble figuring out how to write into the middle of a buffer. For instance, if I'm using a vector, is there a way to say "start writing at index 10" instead of starting at 0?

Thanks for the lib btw! It's been exactly what I was looking for.

**Comment by fraillt** [comment]
Hello,
Good question and it certainly is not obvious how to make it work. 
Writing to output buffer happens through `OutputBufferAdapter` class, and it has a [currentWritePos](../blob/master/include/bitsery/adapter/buffer.h#L211) method, which does what you need.
IMPORTANT: keep in mind that [writtenBytesCount](../blob/master/include/bitsery/adapter/buffer.h#L227) will return the final position in the buffer.
Example: if you set `currentWritePos` to 10 and write 4 bytes, `writtenBytesCount` will return 14, not 4.
Here, is a modified main function of [basic_usage](../blob/master/examples/basic_usage.cpp) example.
```cpp
int main() {
    //set some random data
    MyStruct data{8941, MyEnum::V2, {15.0f, -8.5f, 0.045f}};
    MyStruct res{};
    data.tmp.push_back(data);

    //create buffer to store data
    Buffer buffer;

    size_t my_offset = 10;
    // create adapter manually, that later will be moved into serialized (serialized/deserializer always owns adapter)
    OutputAdapter adapter{buffer};
    // set offset (which in turn resizes buffer is necessary)
    adapter.currentWritePos(my_offset);
    // minus my_offset from actual returned value
    auto writtenSize = bitsery::quickSerialization<OutputAdapter>(std::move(adapter), data) - my_offset;
    // add our offset
    auto beginIt = buffer.begin() + my_offset;

    auto state = bitsery::quickDeserialization<InputAdapter>({beginIt, writtenSize}, res);

    assert(state.first == bitsery::ReaderError::NoError && state.second);
    assert(data.fs == res.fs && data.i == res.i && data.e == res.e);
}

```

Btw, I'm glad you find this library useful!
Happy coding ;)
