### ISSUE TITLE
Only verifying dynamic container size in debug.

### ISSUE THREAD

**Issue by Mmpuskas** [fraillt/bitsery#70]
Hey, this might be intended but I just wanted to double check.

In the dynamic container functions, assert() is being used to verify that the given container isn't too large. [(Link)](https://github.com/fraillt/bitsery/blob/d7876808195834f05fd84619b8f6b266e5c1d5bd/include/bitsery/serializer.h#L292)
This won't trigger in release builds with NDEBUG defined. I noticed it because I was getting an unused parameter warning on maxSize. Is this intended?

**Comment by fraillt** [comment]
Hi, this is intended, although unused parameter warning on release builds is something that should be fixed.

**Comment by fraillt** [comment]
removed unused parameter warning on release in [v5.2.0](../releases/tag/v5.2.0).
