### ISSUE TITLE
Passing a bitsery buffer to a C API

### ISSUE THREAD

**Issue by VelocityRa** [fraillt/bitsery#71]
I want to pass some serialized state to a C API, but I don't really see a way of doing that without an additional copy.
By "additional copy" I mean, currently I am using a `std::vector` `BufferWriter`. The `std::vector` will be destroyed after my C API call returns because of RAII. I can't stop that. So I have to use `malloc` + copy that data somewhere else, which is wasteful.

To be clear, I am the developer of that C API. I want to expose "load" and "save" functions for some state.
So perhaps I could use an opaque pointer that holds a `new`ed `std::vector`? But that sounds hacky.
Maybe there's a solution where `OutputBufferAdapter` can be implemented to use `malloc` + `realloc`.

Excuse my quick + maybe unclear problem description.
Also if this is not currently feasible, I understand.

Thanks.

**Comment by fraillt** [comment]
If I understood your problem correctly, you can use C-style array or even pointer+size as a buffer. [Here](https://github.com/fraillt/bitsery/blob/master/include/bitsery/traits/core/traits.h#L163) is specializations provided for both cases. Also you could look at working example [here](https://github.com/fraillt/cpp_serializers_benchmark/blob/master/bitsery/bitsery_fixed_buffer.cpp)

**Comment by VelocityRa** [comment]
Right, but that example is for a C static array. I don't know the total size of the serialized data that will be saved ahead of time.
I have lots of objects serialized recursively and some are dynamic.
I don't see a specialization there that would allow for that use-case I think.
For example, a possible solution would be to have bitsery a `malloc`ed buffer of some initial size, and then it would `realloc` as it needs space (just as it does `.push_back` for `std::vector` `OutputBufferAdapter`s). Or just give it a `**` and it would `malloc` too and put the pointer there.

Hopefully I explained the problem more clearly now.

**Comment by fraillt** [comment]
You left with only one solution then. You will need to provide a custom buffer implementation and specialize it for `ContainerTraits` and `BufferAdapterTraits`. Hope that helped:)

**Comment by VelocityRa** [comment]
Ok I see, thank you.
