### ISSUE TITLE
The std::variant extension always reinitialies the object on deserialization

### ISSUE THREAD

**Issue by robbert-vdh** [fraillt/bitsery#76]
I noticed that bitsery's `bitsery::ext::StdVariant` always recreates the `std::variant` object even if the object is already holding the variant we want to deserialize. For simple structs this won't make much of a difference, but I'm using `std::variant`s to store audio buffers that can contain either single or double precision floating point samples, and reinitializing these buffers every audio processing cycle gets very expensive. I wrongly assumed that bitsery would just deserialize in-place if possible, but that doesn't seem to be the case.

I fixed this in my own code by simply modifying `bitsery::ext::StdVariant` to reuse the existing object if the requested variant is active [like this](https://github.com/robbert-vdh/yabridge/commit/6ee905c79f6bdc89037868bedbbd4396b1f6e7f5#diff-9d7a9eb2c13648cde4cf7a3b4f720f21e1178bf1c8508c920f637dcd4712bf76R49-R60), but there may be a more elegant solution here.

**Comment by fraillt** [comment]
That is a really good observation.
For primitive types, like std::variant<int,float,bool,..., etc> it should be faster, as there's `if branch`, but we need to fix this for the general case, so you avoid having bad surprises.
As for implementation, I think we can use `get_if` instead of `holds_alternative`.
```cpp
if (auto item = std::get_if<TElem>(&data)) {
	this->serializeType(des, *item);
} else {
	TElem item = ::bitsery::Access::create<TElem>();
	this->serializeType(des, item);
	data = std::variant<Ts...>(std::in_place_index_t<Index>{},
							   std::move(item));
}
```
So if you could update `StdVariant` with this functionality and make a PR, I would be very grateful.

**Comment by robbert-vdh** [comment]
Ah, didn't know about `std::get_if`, that's much cleaner indeed (and the STL/compiler can potentially optimize that better). Would it make sense to only do this for nontrivial types, so primitive types and simple C-compatible structs will still be recreated when de serializing like they are now? So then it would become this:

```cpp
// Reinitializing nontrivial types may be expensive especially when they
// reference heap data, so if `data` is already holding the requested
// variant then we'll deserialize into the existing object
if constexpr (std::is_trivial_v<TElem>) {
    if (auto item = std::get_if<TElem>(&data)) {
        this->serializeType(des, *item);
        return;
    }
}

TElem item = ::bitsery::Access::create<TElem>();
this->serializeType(des, item);
data = std::variant<Ts...>(std::in_place_index_t<Index>{}, std::move(item));
```

Or: (if you'd rather have duplicated code rather than an early return)

```cpp
if constexpr (std::is_trivial_v<TElem>) {
    if (auto item = std::get_if<TElem>(&data)) {
        this->serializeType(des, *item);
    } else {
        TElem item = ::bitsery::Access::create<TElem>();
        this->serializeType(des, item);
        data = std::variant<Ts...>(std::in_place_index_t<Index>{},
                                    std::move(item));
    }
} else {
    TElem item = ::bitsery::Access::create<TElem>();
    this->serializeType(des, item);
    data = std::variant<Ts...>(std::in_place_index_t<Index>{},
                                std::move(item));
}
```

**Comment by fraillt** [comment]
Sure, great idea!
Since we're already in the land of C++17, we can as well use `if constexpr`.
For me version with early return looks cleaner and probably less error-prone, as there's no duplication, but both would work just fine.

**Comment by robbert-vdh** [comment]
Yeah I also prefer the early return version! But I wasn't quite sure about bitsery's code style since some projects don't allow early returns (that's mainly a C-thing for obvious reasons, but still), so I thought I'd just ask first. I've submitted pull request #77 with this change!
