### ISSUE TITLE
Proper way to determine required buffer size before serializing?

### ISSUE THREAD

**Issue by Net5F** [fraillt/bitsery#89]
Hello, I'm trying to allocate a buffer, then serialize an object into it.

I'm using the following to find the supposed size of the object.
```
std::size_t measuredSize = bitsery::quickSerialization(bitsery::MeasureSize{}, objectToSerialize);
```

From testing, I know that `measuredSize` matches what is returned when I actually serialize the object (24B).

The issue is, I'm running into the following assert, which is seeing newOffset go up to 27B and thus fails.
https://github.com/fraillt/bitsery/blob/d24e0ab1b3daaa92219b60a57dca51fa8e23103f/include/bitsery/adapter/buffer.h#L309

How can I go about figuring out how large the buffer actually needs to be?

**Comment by fraillt** [comment]
Looks like a bug, could you share a working example of this? So I could reproduce and dive deeper?

**Comment by Net5F** [comment]
It turns out that the 24B measurement is perfectly accurate, I just forgot that I'm writing my data into the buffer with a 3B offset. Figured it out while writing up an example.

Sorry for the trouble. Thanks for the help!
