### ISSUE TITLE
Can I parse bitsery-serialized buffer using Python struct.unpack?

### ISSUE THREAD

**Issue by nicktrandafil** [fraillt/bitsery#92]
Is it safe to assume binary format of bitsery?

I mean, having the struct
```cpp
struct A {
    template <typename S>
    void serialize(S& s) {
        s.value4b(x);
        s.value2b(y);
    }
    uint32_t x;
    uint16_t y;
};
```
can I safely parse it using Python `struct.unpack("=IH", bisery_binary_data)`?

More generally, can I assume that consecutive calls to `s.valueNb(...)` will compose a buffer consisting of consecutively `memcpy`ied chunks of data of exact size without any padding?

**Comment by fraillt** [comment]
Yes, bitsery is explicitly verbose, so you could know exactly what to expect, in this case it will always be 4+2bytes,- no padding.
Endianess is specified by bitsery config and by default is little-endian.

**Comment by nicktrandafil** [comment]
Thanks.
