### ISSUE TITLE
Are there any single header version available?

### ISSUE THREAD

**Issue by hitdshu** [fraillt/bitsery#93]
Hi,

Thanks for your excellent project. Are there any single header version available?

Best

**Comment by fraillt** [comment]
Thanks, I'm glad you found it useful:) Unfortunately, there's no single header variant. In fact, I tried to minimize dependencies, so it could be used in a constrained environments (e.g. embedded).

**Comment by hitdshu** [comment]
Thanks for your very timely reply. With a single header version, one can use it very easily in his project. 

As you said, this project is already quite lightweight. So I'll try to use it directly. Thanks for your very excellent work.

Best,
Deshun
