### ISSUE TITLE
Does this use dynamic allocation?

### ISSUE THREAD

**Issue by sergerold** [fraillt/bitsery#95]
Hi

Does this use dynamic allocation? I'd like to use on an arduino.

Thanks

**Comment by fraillt** [comment]
Hi, no it doesn't in general. All extensions that allocates thought, accepts custom allocator as well.

**Comment by TheCutter** [comment]
@sergerold Did you get the library running on an arduino/ESP?

**Comment by eyalz800** [comment]
Even if it does allocate, did you see if you can just use a custom heap allocator locally? I rolled my own once when I needed for embedded  https://github.com/eyalz800/zpp_allocator, it’s pretty transparent
