### ISSUE TITLE
Parallel read and write?

### ISSUE THREAD

**Issue by BotellaA** [fraillt/bitsery#97]
This is not an issue but a general question/reflection.

Is there a way, or do you see a way to use Bitsery in parallel?
It looks challenging but maybe some clever way to split the file into several pieces.
Or perhaps another idea?

**Comment by fraillt** [comment]
Serialization is very linear/serial process, especially for bitsery as it tries to save space for containers and there are some extensions as well. For this reason I guess you can only do it manually when you know some specific properties of your data.
Just split your data so you could serialize in parallel, and then merge the buffers, either serializing them as bytes (this will also allow you to deserialize in parallel) or simply concatenate them.
