### ISSUE TITLE
Writing to pointer to uint8_t array

### ISSUE THREAD

**Issue by sergerold** [fraillt/bitsery#98]
Apologies if this is a stupid question - I have researched it quite a bit but couldn't work out where I am going wrong.

Basically, I'd like to be able to pass a pointer to a buffer to a function and for that function to then call the quickSerialisation function (Message is my class which I'd like to serialise):

```
using Buffer = uint8_t[10];
using OutputAdapter = bitsery::OutputBufferAdapter<Buffer>;

size_t getBinary(const Message& msg, uint8_t *buff)
{
    return bitsery::quickSerialization(OutputAdapter{buff}, msg);
}

```
(I have a serialize method for Message class which is not provided above)
But this gives an error:
```

error: no matching function for call to 'bitsery::OutputBufferAdapter<unsigned char [10]>::OutputBufferAdapter(<brace-enclosed initializer list>)'

buffer.h:210:29: note:   no known conversion for argument 1 from 'uint8_t*' {aka 'unsigned char*'} to 'bitsery::OutputBufferAdapter<unsigned char [10]>&&'
  210 |         OutputBufferAdapter(OutputBufferAdapter&&) = default;
```

I don't get this error with:

```
using Buffer = uint8_t[10];
using OutputAdapter = bitsery::OutputBufferAdapter<Buffer>;

size_t getBinary(const Message& msg)
{
    Buffer buff;
    return bitsery::quickSerialization(OutputAdapter{buff}, msg);
}

```
Is this to do with pointer decay?

Thanks very much

**Comment by fraillt** [comment]
`size_t getBinary(const Message& msg, uint8_t *buff)`.
`buff` is not correct type here. Your buffer is fixed size, so your argument must be fixed size as well, like this: `uint8_t (&buff)[10]`. I agree this is not obvious syntax, but I hope this should solve your problem:)
